-- Generated by Layre Plugin

local Fusion = require(game.ReplicatedStorage.Packages.Shared.Utility.Fusion)
local UIPaths = require(script.Parent.UIPaths)

export type Scope = Fusion.Scope & {
	AttributeValue: (self: Scope, Attribute: string, DefaultValue: any) -> Fusion.Value;
	Paths: UIPaths.Paths;
--comps
--stores
}

return {}
